import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import { loadData, saveData, totot } from "../lib/loadOrSave.js";
import DisplayData from "../components/DisplayData.jsx";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Dash Board</h1>

      <DisplayData />
    </div>
  );
}
