import Head from "next/head"
import Image from "next/image"
import { useState } from "react"
import { loadData, saveData, totot } from "../lib/loadOrSave.js"
import DisplayData from "../components/DisplayData.jsx"
import styles from "../styles/earnOrLoose.module.css"

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.centered}>
        <h1>Dash Board</h1>

        <DisplayData />
      </div>
    </div>
  )
}
